"""Bounded Phase 4 vision observation contracts and pure analysis service."""

from core.vision.contracts import (
    ANALYSIS_TTL_SECONDS,
    CANONICAL_ID_PATTERN,
    MAX_CONFIDENCE_MILLI,
    MAX_OBSERVATION_TEXT_LENGTH,
    MAX_OBSERVATIONS,
    MIN_CONFIDENCE_MILLI,
    MIN_OBSERVATION_TEXT_LENGTH,
    ContractValidationError,
    VisionAnalysisRecord,
    VisionAnalysisRequest,
    VisionAnalysisState,
    VisionCapability,
    VisionObservation,
    VisionObservationKind,
    VisionOutcomeCode,
    VisionProcessingMode,
    VisionServiceOutcome,
    validate_analysis_id,
    validate_canonical_id,
    validate_handoff_id,
    validate_request_id,
    validate_transfer_id,
)
from core.vision.service import VisionAnalysisService
from core.vision.runtime import CloudVisionAnalyzer, DescriptionAnalyzer, VisionRuntime
from core.vision.cloud import (
    BoundedGatewayRequestRunner,
    CloudVisionConfigurationError,
    GatewayVisionAdapter,
    GatewayVisionConfig,
    GatewayVisionRouter,
    create_optional_gateway_vision_router_from_environment,
)
from core.vision.description import (
    BoundedLocalDescriptionRunner,
    DescriptionAdapterError,
    DescriptionAnalyzerResult,
    DescriptionResult,
    DescriptionStatus,
    LocalDescriptionAdapter,
)
from core.vision.mlx_worker import (
    LocalVisionConfig,
    SpawnedMlxDescriptionRunner,
    VisionProvisioningError,
    create_optional_mlx_description_adapter_from_environment,
    load_verified_local_vision_config,
)

__all__ = (
    "ANALYSIS_TTL_SECONDS",
    "CANONICAL_ID_PATTERN",
    "MAX_CONFIDENCE_MILLI",
    "MAX_OBSERVATION_TEXT_LENGTH",
    "MAX_OBSERVATIONS",
    "MIN_CONFIDENCE_MILLI",
    "MIN_OBSERVATION_TEXT_LENGTH",
    "ContractValidationError",
    "VisionAnalysisRecord",
    "VisionAnalysisRequest",
    "VisionAnalysisService",
    "DescriptionAnalyzer",
    "CloudVisionAnalyzer",
    "BoundedGatewayRequestRunner",
    "CloudVisionConfigurationError",
    "GatewayVisionAdapter",
    "GatewayVisionConfig",
    "GatewayVisionRouter",
    "create_optional_gateway_vision_router_from_environment",
    "BoundedLocalDescriptionRunner",
    "DescriptionAdapterError",
    "DescriptionAnalyzerResult",
    "DescriptionResult",
    "DescriptionStatus",
    "LocalDescriptionAdapter",
    "LocalVisionConfig",
    "SpawnedMlxDescriptionRunner",
    "VisionProvisioningError",
    "create_optional_mlx_description_adapter_from_environment",
    "load_verified_local_vision_config",
    "VisionRuntime",
    "VisionAnalysisState",
    "VisionCapability",
    "VisionObservation",
    "VisionObservationKind",
    "VisionOutcomeCode",
    "VisionProcessingMode",
    "VisionServiceOutcome",
    "validate_analysis_id",
    "validate_canonical_id",
    "validate_handoff_id",
    "validate_request_id",
    "validate_transfer_id",
)
