"""Bounded Phase 4 vision observation contracts and pure analysis service."""

from core.vision.contracts import (
    ANALYSIS_TTL_SECONDS,
    CANONICAL_ID_PATTERN,
    MAX_CONFIDENCE_MILLI,
    MAX_OBSERVATION_TEXT_LENGTH,
    MAX_OBSERVATIONS,
    MIN_CONFIDENCE_MILLI,
    MIN_OBSERVATION_TEXT_LENGTH,
    ContractValidationError,
    VisionAnalysisRecord,
    VisionAnalysisRequest,
    VisionAnalysisState,
    VisionCapability,
    VisionObservation,
    VisionObservationKind,
    VisionOutcomeCode,
    VisionServiceOutcome,
    validate_analysis_id,
    validate_canonical_id,
    validate_handoff_id,
    validate_request_id,
    validate_transfer_id,
)
from core.vision.service import VisionAnalysisService
from core.vision.runtime import DescriptionAnalyzer, VisionRuntime
from core.vision.description import (
    BoundedLocalDescriptionRunner,
    DescriptionAdapterError,
    DescriptionAnalyzerResult,
    DescriptionResult,
    DescriptionStatus,
    LocalDescriptionAdapter,
)

__all__ = (
    "ANALYSIS_TTL_SECONDS",
    "CANONICAL_ID_PATTERN",
    "MAX_CONFIDENCE_MILLI",
    "MAX_OBSERVATION_TEXT_LENGTH",
    "MAX_OBSERVATIONS",
    "MIN_CONFIDENCE_MILLI",
    "MIN_OBSERVATION_TEXT_LENGTH",
    "ContractValidationError",
    "VisionAnalysisRecord",
    "VisionAnalysisRequest",
    "VisionAnalysisService",
    "DescriptionAnalyzer",
    "BoundedLocalDescriptionRunner",
    "DescriptionAdapterError",
    "DescriptionAnalyzerResult",
    "DescriptionResult",
    "DescriptionStatus",
    "LocalDescriptionAdapter",
    "VisionRuntime",
    "VisionAnalysisState",
    "VisionCapability",
    "VisionObservation",
    "VisionObservationKind",
    "VisionOutcomeCode",
    "VisionServiceOutcome",
    "validate_analysis_id",
    "validate_canonical_id",
    "validate_handoff_id",
    "validate_request_id",
    "validate_transfer_id",
)
