"""Streaming voice contracts, state machine, and transcript primitives."""

from core.voice_streaming.contracts import (
    AECCapability,
    AccessibilityState,
    AuthDecision,
    CaptionRole,
    CaptureState,
    FinalTranscript,
    InterimTranscript,
    InterruptionConfirmation,
    InterruptionRequest,
    PlaybackState,
    StateTransitionRecord,
    StreamingVoiceFailure,
    VADCapability,
    VADEvent,
    VerifiedWakeEvent,
    VoiceStreamState,
    sanitize_text,
    validate_confidence,
    validate_monotonic_ns,
    validate_stream_id,
)
from core.voice_streaming.state import (
    VoiceStreamStateMachine,
    is_valid_transition,
)
from core.voice_streaming.transcript import StreamingTranscriptAccumulator

__all__ = [
    "AECCapability",
    "AccessibilityState",
    "AuthDecision",
    "CaptionRole",
    "CaptureState",
    "FinalTranscript",
    "InterimTranscript",
    "InterruptionConfirmation",
    "InterruptionRequest",
    "PlaybackState",
    "StateTransitionRecord",
    "StreamingTranscriptAccumulator",
    "StreamingVoiceFailure",
    "VADCapability",
    "VADEvent",
    "VerifiedWakeEvent",
    "VoiceStreamState",
    "VoiceStreamStateMachine",
    "is_valid_transition",
    "sanitize_text",
    "validate_confidence",
    "validate_monotonic_ns",
    "validate_stream_id",
]
